version: '3.8'

services:
  webssh:
    image: huashengdun/webssh:latest
    container_name: webssh
    restart: unless-stopped
    environment:
      - WSSH_PORT=8888
      - WSSH_TIMEOUT=30
      - WSSH_DEBUG=False
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shellhub-web.entrypoints=http"
      - "traefik.http.routers.shellhub-web.rule=Host(`shell.thiagosol.com`)"
      - "traefik.http.routers.shellhub-web-secure.entrypoints=https"
      - "traefik.http.routers.shellhub-web-secure.rule=Host(`shell.thiagosol.com`)"
      - "traefik.http.routers.shellhub-web-secure.tls=true"
      - "traefik.http.routers.shellhub-web-secure.service=shellhub-web-secure"
      - "traefik.http.services.shellhub-web-secure.loadbalancer.server.port=8888"
      - "traefik.docker.network=external-sol-apis"
    networks:
      - logging-network
      - external-sol-apis
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "service=shell-hub-web,type=service"
        loki-retries: "5"
        loki-batch-size: "400"
        mode: "non-blocking"
    deploy:
      resources:
        limits:
          memory: 100M

networks:
  logging-network:
    external: true
  external-sol-apis:
    external: true
