version: '3.8'

services:
  shell-hub:
    image: shell-hub
    container_name: shell-hub
    pull_policy: never
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shellhub-web.entrypoints=http"
      - "traefik.http.routers.shellhub-web.rule=Host(`shell.thiagosol.com`)"
      - "traefik.http.routers.shellhub-web-secure.entrypoints=https"
      - "traefik.http.routers.shellhub-web-secure.rule=Host(`shell.thiagosol.com`)"
      - "traefik.http.routers.shellhub-web-secure.tls=true"
      - "traefik.http.routers.shellhub-web-secure.service=shellhub-web-secure"
      - "traefik.http.services.shellhub-web-secure.loadbalancer.server.port=80"
      - "traefik.docker.network=external-sol-apis"
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "service=shell-hub,type=service"
        loki-retries: "5"
        loki-batch-size: "400"
        mode: "non-blocking"
    depends_on:
      - wetty       
    networks:
      - wetty-network
      - logging-network
      - external-sol-apis
    deploy:
      resources:
        limits:
          memory: 50M  
    
  wetty:
    image: butlerx/wetty:latest
    container_name: wetty
    restart: unless-stopped
    environment:
      - SSHHOST=${SHELL_SSH_SERVER}
      - SSHPORT=22
      - SSH_OPTIONS=-i /root/.ssh/deploy_key
    volumes:
      - /opt/auto-deploy/ssh/deploy_key:/root/.ssh/deploy_key:ro
      - ./run.sh:/run.sh
    command: ["/bin/sh", "/run.sh"]
    networks:
      - wetty-network
      - logging-network  
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "service=wetty,type=service"
        loki-retries: "5"
        loki-batch-size: "400"
        mode: "non-blocking"
    deploy:
      resources:
        limits:
          memory: 50M  

networks:
  wetty-network:
    external: true
  logging-network:
    external: true
  external-sol-apis:
    external: true
